version: '3.8'

services:
  # FastAPIバックエンドサービス
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fastapi_diary_api
    restart: always
    # ポートマッピング: ホストの8000番ポートをコンテナの8000番ポートに接続
    ports:
      - "8000:8000"
    # ローカルの環境変数ファイルを読み込む（キーはファイル内に記述）
    env_file:
      - .env.local
    # ホットリロードのためのボリュームマウント（開発中の変更を即時反映）
    volumes:
      - ./backend:/app
    # 開発中はホットリロードを有効にしたコマンドで上書き（本番ではDockerfileのCMDが使われる）
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload